### Métodos ALgebricos

In [86]:
import numpy as np 




# Operações com vetores

def SomaVetores(x, y):
    
    np.sum(x, y)

def MultiplicaEscalarVetor(a, x):    
    np.dot(a, x)


def ProdutoInterno(x, y):
    return np.dot(x, y)

In [87]:


#Normas 

def Norma1(x):
    return np.sum(np.abs(x))
def Norma2(x):
    return np.sqrt(np.sum(np.abs(x)**2))
def NormaInfinito(x):
    return np.max(np.abs(x))
def Normap(x, p):
    return np.sum(np.abs(x)**p)**(1/p)
def NormaSoma(x, y):
    return np.sqrt(Norma2(x)**2 + Norma2(y)**2 + 2*ProdutoInterno(x, y))
def NormaSubtracao(x, y):
    return np.sqrt( (Norma2(x)) **2 + (Norma2(y))**2 - 2*ProdutoInterno(x, y))

# Distâncias

def DistanciaCaracteristicas(x, y):
    
    return NormaSubtracao(x, y)

def Vizinhanca(x,z):
    # X é o ponto base 
    # Z é uma lista de pontos, a qual queremos o de menor distância
    
    proximo = z[0]
    
    for i in range(len(z)):
        if DistanciaCaracteristicas(x, z[i]) < DistanciaCaracteristicas(x, proximo):
            proximo = z[i]
            
    return proximo


# Aplicação Normalização

def NormalizaVetor(x):
    return x/Norma2(x)

def BaseOrtonormal(beta,x):
    
    #x é o vetor que queremos a base ortonormal
    #beta é a base ortonormal
    xnormal = []
    
    if len(beta) != len(x):
        print("Erro, dimensões diferentes")
        return
    else:
        
        for i in range(len(beta)):
            
            xnormal.append(ProdutoInterno(x, beta[i])*beta[i])
        
        return xnormal

def AnguloVetores(x, y):
    
    return np.arccos(  ( ProdutoInterno(x, y)/(Norma2(x)*Norma2(y)) )  )    





In [120]:


# Algoritmos

# Posto de uma matriz = número de vetores linearmente independentes

def GramSchmidt(a, tol=1e-10):
    q = []
    for i in range(len(a)):
        qtilde = np.array(a[i], dtype=np.float64)  # Convert to float64 explicitly
        for j in range(i):
            qtilde -= np.dot(q[j], a[i]) * q[j]
        if np.linalg.norm(qtilde) < tol:
            print("Os vetores são linearmente dependentes.")
            return q
        print(qtilde)
        q.append(qtilde / np.linalg.norm(qtilde))
    return q

def PostoMatriz(a):
    
    return len( GramSchmidt(a) )


def MatrizPositivaDefinida(A):
    
    if np.all(np.linalg.eigvals(A) != 0):
        return True
def MatrizAumentada(A, b):
    
    return  np.hstack((A, b.reshape((-1, 1))))

def TriangularSuperior(matrix):
    rows, cols = matrix.shape
    for i in range(rows):
        for j in range(i + 1, cols):
            if matrix[i, j] != 0:
                return False
    return True

def TriangularInferior(matrix):
    rows, cols = matrix.shape
    for i in range(rows):
        for j in range(0, i):
            if matrix[i, j] != 0:
                return False
    return True


def GaussianElimination(A): #matriz aumentada
    
    m,n = A.shape    
    A = np.array(A, dtype=np.float64)
    for k in range(n-1):        
        j = k
        while j < n: # Passo 1 
            
            if A[k,j] != 0:
                break
            else :                
                for r in range(k+1, m):                    
                    if A[r,j] != 0: # Acha um pivo diferente de zero                        
                        A[k,r] = A[r,k] # Troca as linhas para que o pivo fique na linha mais a esquerda possível                        
                        break                    
                else:                    
                    j += 1                                    
        # Passo 2        
        for i in range(k+1, m):            
            A[i] = A[i] - (A[i,j]/A[k,j])*A[k]    
    return A

def SistemSolverTS(A):
    n = A.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1): # Triangular superior
        x[i] = (A[i, -1] - np.dot(A[i, i+1:n], x[i+1:n])) / A[i, i]

    return x
def SistemSolverTI(A):
    n = A.shape[0]
    x = np.zeros(n)
    for i in range(n): # Triangular inferior
        x[i] = (A[i, -1] - np.dot(A[i, :i], x[:i])) / A[i, i]

    return x

def SistemSolver(A):
    
    n = A.shape[0]
    
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i+1:n], x[i+1:n])) / A[i, i]

    return x


def LUDecomposer(A):
    
    if MatrizPositivaDefinida(A) != True:
        print("A matriz não é positiva definida")
        return
    else :
        
        n = A.shape[0]
        L = np.eye(n)
        U = np.zeros((n, n))
        for i in range(n):
            for j in range(i+1):
                U[j, i] = A[j, i] - np.dot(L[j, :j], U[:j, i])
            for j in range(i+1, n):
                L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
        return L, U
    
    
def CholeskyDecomposer(A):
    
    if MatrizPositivaDefinida(A) != True :
        print("A matriz não é positiva definida")
        return
    else :
        
        n = A.shape[0]
        L = np.zeros((n, n))
        for i in range(n):
            for j in range(i+1):
                s = np.dot(L[i, :j], L[j, :j])
                if i == j:
                    L[i, j] = np.sqrt(A[i, i] - s)
                else:
                    L[i, j] = (A[i, j] - s) / L[j, j]
        return L
                    
                    
                
def jacobi_richardson(A, b, tol, maxiter):
    n = len(b)
    x = np.zeros(n)
    nb = np.linalg.norm(b)
    res = np.zeros(maxiter + 1)
    res[0] = nb
    
    for k in range(maxiter):
        xnovo = np.zeros(n)
        for i in range(n):
            for j in range(n):
                if j != i:
                    xnovo[i] += A[i, j] * x[j]
            xnovo[i] = (b[i] - xnovo[i]) / A[i, i]
        x = xnovo
        res[k + 1] = np.linalg.norm(np.dot(A, x) - b)
        
        if res[k + 1] / nb < tol:
            return x, res[:k + 1]
    
    return x, res


def gradiente_conjugado(A, b, x, M):
    r = b - np.dot(A, x)
    
    for k in range(M):
        t = np.dot(r, r) / np.dot(r, np.dot(A, r))
        x = x + t * r
        r = r - t * np.dot(A, r)
        
        print("Iteração:", k, " Tamanho do passo:", t, " x:", x, " r:", r)
    
    return x, r

def gradiente_conjugado(A, b, x, M):
    r = b - np.dot(A, x)
    
    for k in range(M):
        t = np.dot(r, r) / np.dot(r, np.dot(A, r))
        x = x + t * r
        r = r - t * np.dot(A, r)
        
        print("Iteração:", k, " Tamanho do passo:", t, " x:", x, " r:", r)
    
    return x, r



## AFA 1

### Exercício 3.

Dado o conjunto V = {v1, v2, v3, v4, v5, v6}, onde
v1 = [1,2,3,4], 
v2 = [0,5,−1,3],
v3 = [−4,−3,2,1],
v4 = [−,1,−7,3,−7/3],
v5 = [1,−4,−6,-2],
v6 = [3,2,−1/4,2]

In [89]:
## Correção da questão 3 da lista de exercícios

# Verifica Ortogonalidade


v1 = [1,2,3,4]
v2 = [0,5,-1,3]
v3 = [-4,-3,2,1]
v4 = [-1,-7,3,-2.3333]
v5 = [1,-4,-6,-2]
v6 = [3,2,-0.25,2]

V = np.array([v1,v2,v3,v4,v5,v6],dtype="object")

for i in range(len(V)):
    for j in range(i,len(V)):
        if i != j:
            print("Produto interno entre v",i+1," e v",j+1,": ", ProdutoInterno(V[i],V[j]))

Produto interno entre v 1  e v 2 :  19
Produto interno entre v 1  e v 3 :  0
Produto interno entre v 1  e v 4 :  -15.3332
Produto interno entre v 1  e v 5 :  -33
Produto interno entre v 1  e v 6 :  14.25
Produto interno entre v 2  e v 3 :  -14
Produto interno entre v 2  e v 4 :  -44.9999
Produto interno entre v 2  e v 5 :  -20
Produto interno entre v 2  e v 6 :  16.25
Produto interno entre v 3  e v 4 :  28.6667
Produto interno entre v 3  e v 5 :  -6
Produto interno entre v 3  e v 6 :  -16.5
Produto interno entre v 4  e v 5 :  13.666599999999999
Produto interno entre v 4  e v 6 :  -22.4166
Produto interno entre v 5  e v 6 :  -7.5


In [90]:
# Verifica Angulos:


for i in range(len(V)):
    for j in range(i,len(V)):
        if i != j:
            print("Angulo entre v",i+1," e v",j+1,": ", AnguloVetores(V[i],V[j]))


Angulo entre v 1  e v 2 :  0.9442473545867198
Angulo entre v 1  e v 3 :  1.5707963267948966
Angulo entre v 1  e v 4 :  1.9270040069334677
Angulo entre v 1  e v 5 :  2.49480519746212
Angulo entre v 1  e v 6 :  0.8894441470679866
Angulo entre v 2  e v 3 :  2.0175602879101473
Angulo entre v 2  e v 4 :  2.816162498730185
Angulo entre v 2  e v 5 :  2.035070208212683
Angulo entre v 2  e v 6 :  0.8433509628782423
Angulo entre v 3  e v 4 :  0.860622133841933
Angulo entre v 3  e v 5 :  1.7164055673877163
Angulo entre v 3  e v 6 :  2.38808423797738
Angulo entre v 4  e v 5 :  1.3433484740176547
Angulo entre v 4  e v 6 :  2.3131372783928406
Angulo entre v 5  e v 6 :  1.8136700887016526


In [91]:
np.arccos((ProdutoInterno(v1,v3)/Norma2(v1)*Norma2(v3)))

1.5707963267948966

In [92]:
# Gerar todos os possíveis subconjuntos de v com 4 vetores e verificar se formam uma base

# C 6,4 = 15

#Separar as combinações de quatro vetores possíveis

for i in range(len(V)):
    for j in range(i+1,len(V)):
        for k in range(j+1,len(V)):
            for l in range(k+1,len(V)):
                print("Combinação: v%d,v%d,v%d,v%d"%(i,j,k,l),V[i],V[j],V[k],V[l])
                #print(V[i],V[j],V[k],V[l])
                # verificar se formam uma base
                A = np.array([V[i],V[j],V[k],V[l]], dtype="float64")
                #print(A)
                det = np.linalg.det(A)
                if det != 0:
                    
                    print("Formam uma base, det: ", det)
                else:
                    print("LD!!")

Combinação: v0,v1,v2,v3 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [-1 -7 3 -2.3333]
Formam uma base, det:  0.0024999999999941766
Combinação: v0,v1,v2,v4 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [1 -4 -6 -2]
Formam uma base, det:  534.0000000000001
Combinação: v0,v1,v2,v5 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [3 2 -0.25 2]
Formam uma base, det:  133.4999999999999
Combinação: v0,v1,v3,v4 [1 2 3 4] [0 5 -1 3] [-1 -7 3 -2.3333] [1 -4 -6 -2]
Formam uma base, det:  178.00169999999994
Combinação: v0,v1,v3,v5 [1 2 3 4] [0 5 -1 3] [-1 -7 3 -2.3333] [3 2 -0.25 2]
Formam uma base, det:  44.501674999999985
Combinação: v0,v1,v4,v5 [1 2 3 4] [0 5 -1 3] [1 -4 -6 -2] [3 2 -0.25 2]
Formam uma base, det:  267.00000000000006
Combinação: v0,v2,v3,v4 [1 2 3 4] [-4 -3 2 1] [-1 -7 3 -2.3333] [1 -4 -6 -2]
Formam uma base, det:  711.9987000000006
Combinação: v0,v2,v3,v5 [1 2 3 4] [-4 -3 2 1] [-1 -7 3 -2.3333] [3 2 -0.25 2]
Formam uma base, det:  177.9996750000001
Combinação: v0,v2,v4,v5 [1 2 3 4] [-4 -3 2 1] [1 -4 -6 -2] [3 2 -0.25

In [93]:
Z  = np.array([[ 1,  2,  3, 4],[ 0,  5,-1, 3],[-4,-3, 2, 1],[ 1,-4,-6,-2]], dtype="float64")

h = np.array([[1,0],[0,2]], dtype="float64")

In [94]:
np.linalg.det(Z)

534.0000000000001

In [95]:
# Calcular Normas 1,2,infinito para cada vetor

for i in range(len(V)):
    print("Norma 1 de v%d: "%(i+1), Norma1(V[i]))
    print("Norma 2 de v%d: "%(i+1), Norma2(V[i]))
    print("Norma infinito de v%d: "%(i+1), NormaInfinito(V[i]))

Norma 1 de v1:  10
Norma 2 de v1:  5.477225575051661
Norma infinito de v1:  4
Norma 1 de v2:  9
Norma 2 de v2:  5.916079783099616
Norma infinito de v2:  5
Norma 1 de v3:  10
Norma 2 de v3:  5.477225575051661
Norma infinito de v3:  4
Norma 1 de v4:  13.3333
Norma 2 de v4:  8.027720030618905
Norma infinito de v4:  7
Norma 1 de v5:  13
Norma 2 de v5:  7.54983443527075
Norma infinito de v5:  6
Norma 1 de v6:  7.25
Norma 2 de v6:  4.130677910464576
Norma infinito de v6:  3


In [96]:
### Questão 6

def a(x):
    
    return np.max(np.abs(x[:-1])) # Norma infinito de 1 ate n-1

def b(x):
    return np.sum(np.abs(x**3))

def c(x):
    return np.sum(np.abs(x**2)**(1/2))

def d(x):
    
    soma = 0
    for i in range(len(x)):
       soma += np.abs((2**-i)*x[i])
    
    return soma

In [97]:
# Verificar Norma:

#||u|| >= 0
#||u+v|| <= ||u|| + ||v||
#||au|| = |a|*||u||

u = np.array([1,0,1])
v = np.array([-2,1,0])

print(a(u+v) <= a(u) + a(v),a(2*u) == 2*a(u),a(u) >= 0 )
print(b(u+v) <= b(u) + b(v),b(2*u) == 2*b(u),b(u) >= 0 )
print(c(u+v) <= c(u) + c(v),c(2*u) == 2*c(u),c(u) >= 0 )
print(d(u+v) <= d(u) + d(v),d(2*u) == 2*d(u),d(u) >= 0 )



True True True
True False True
True True True
True True True


In [98]:
# Questão 8


a1 = np.array([1,1,0])
a2 = np.array([0,1,1])
a3 = np.array([1,0,1])

beta = [a1,a2,a3]


# base ortonormal

beta = GramSchmidt(beta)

for i in range(len(beta)):
    print("Norma 2 do vetor %d: "%(i+1), Norma2(beta[i]))

[1. 1. 0.]
[-0.5  0.5  1. ]
[ 0.66666667 -0.66666667  0.66666667]
Norma 2 do vetor 1:  0.9999999999999999
Norma 2 do vetor 2:  1.0
Norma 2 do vetor 3:  1.0


In [99]:
# Questão 9

beta  = np.empty((3,3), dtype="float64")



a1 = np.array([1,0,0, 0,0,0, 0,0,0,0])
a2 = np.array([1,1,0, 0,0,0, 0,0,0,0])
a3 = np.ones(10)
beta = np.array([a1,a2,a3], dtype="float64")
GramSchmidt(beta)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]


[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0.        , 0.        , 0.35355339, 0.35355339, 0.35355339,
        0.35355339, 0.35355339, 0.35355339, 0.35355339, 0.35355339])]

In [100]:

# Questão 1 EXO1

""" 
Dados os seguintes vetores em R4
v1=⎡⎣⎢⎢⎢1234⎤⎦⎥⎥⎥,v2=⎡⎣⎢⎢⎢−4−321⎤⎦⎥⎥⎥ev3=⎡⎣⎢⎢⎢1−4−6−2⎤⎦⎥⎥⎥
. 

  Verifique:

 ∥v1∥∞≤∥v2∥1+∥v3∥2
 em branco
 ∥v3∥2≥∥v1∥1+∥v2∥∞
 em branco
 ∥v1−v2∥2≥∥v1−v2∥1
 em branco
 ∥v2−v3∥1≥∥v1−v3∥∞
 em branco"""
 
 
v1 = np.array([1,2,3,4])
v2 = np.array([-4,-3,2,1])
v3 = np.array([1,-4,-6,-2])

print(NormaInfinito(v1) <= Norma1(v2) + Norma2(v3))
print(Norma2(v3) >= Norma1(v1) + NormaInfinito(v2))
print(Norma2(v1-v2) >= Norma1(v1-v2))
print(Norma1(v2-v3) >= NormaInfinito(v1-v3))

True
False
False
True


In [101]:
# Questão 2 EXO1

"""  
Dado  x=⎡⎣⎢⎢⎢⎢x1x2⋮xn⎤⎦⎥⎥⎥⎥∈Rn
 . Determine se a expressão:
N(x)=∑i=1n|xi|3

  define uma norma em Rn
.
"""

def NormaCuboAbs(x):
    return np.sum(np.abs(x**3))
  
if NormaCuboAbs(v1) >= 0 and NormaCuboAbs(2*v1) == 2*NormaCuboAbs(v1) and NormaCuboAbs(v1+v2) <= NormaCuboAbs(v1) + NormaCuboAbs(v2):
    print("True")
else:
    print("False")  
    

    


False


In [102]:
# Questão 3 EXO1
""" 

Dados os seguintes vetores a1=⎡⎣⎢100⎤⎦⎥,a2=⎡⎣⎢110⎤⎦⎥,a3=⎡⎣⎢111⎤⎦⎥
 . 

  Desta forma:

Verifique que {a1,a2,a3}
 é uma base para o R3
;
Construir, a partir destes vectores, uma base ortonormal para o R3
.



"""
n1 = np.array([1,0,0])
n2 = np.array([1,1,0])
n3 = np.array([1,1,1])

if np.linalg.det(np.array([n1,n2,n3])) != 0:
    print("Formam uma base")
    #Construir, a partir destes vectores, uma base ortonormal para o R3

    

        # base ortonormal

    n = n1, n2, n3

    m = GramSchmidt(n)

    for i in range(len(m)):
        print("Norma 2 do vetor %d: "%(i+1), Norma2(m[i]))


Formam uma base
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]
Norma 2 do vetor 1:  1.0
Norma 2 do vetor 2:  1.0
Norma 2 do vetor 3:  1.0


In [103]:
# Questão 4 EXO1

"""  
Para uma matriz A∈Rn×n
 elabore um Algoritmo que:

  Multiplique o escalar c∈R
 a todos os elementos da coluna j
, onde j=1,…,n
, da matriz A
.

"""



def ProdutoColuna(A,k):
    print("matriz original: \n", A)
    print("\nmatriz modificada: \n")
    for j in range(len(A)):
        
       A[:,j] = A[:,j]*k
    print(A)


matriz =   np.array([[1,1,0],[0,1,0],[1,-2,0]], dtype="float64")

ProdutoColuna(matriz, 2)


matriz original: 
 [[ 1.  1.  0.]
 [ 0.  1.  0.]
 [ 1. -2.  0.]]

matriz modificada: 

[[ 2.  2.  0.]
 [ 0.  2.  0.]
 [ 2. -4.  0.]]


In [104]:
#Normas matriciais

def Norma1Coluna(A):
    
    somaColuna = []
    
    for j in range(len(A)):
        
       somaColuna.append(np.sum(np.abs(A[:,j])))
    
    return np.max(somaColuna)

def NormaInfinitoLinha(A):
    
    somaLinha = []
    
    for i in range(len(A)):
        
       somaLinha.append(np.sum(np.abs(A[i,:])))
    
    return np.max(somaLinha)
    
    
def NormaFrobenius(A):
    
    soma = 0
    
    for i in range(len(A)):
        for j in range(len(A)):
            soma += np.abs(A[i,j])**2
    
    return np.sqrt(soma)

In [105]:
A = np.array([[3, -1, 1],[3, 6 ,2],[3, 3 ,7]])

#Noma1Coluna(A)
#NormaInfinitoLinha(A)
NormaFrobenius(A)

11.269427669584644

In [106]:
# Questão 5 EXO1

"""

Dadas as seguintes matrices em R3×3
A=⎡⎣⎢100210321⎤⎦⎥,B=⎡⎣⎢1−111101−10⎤⎦⎥,C=⎡⎣⎢400010002⎤⎦⎥eD=⎡⎣⎢100110011⎤⎦⎥

"""

A  = np.array([[1,2,3],[0,1,2],[0,0,1]])
B = np.array([[1,1,1],[-1,1,-1],[1,0,0]])
C = np.array([[4,0,0],[0,1,0],[0,0,2]])
D = np.array([[1,1,0],[0,1,1],[0,0,1]])

print(NormaFrobenius(D) > Norma1Coluna(B)+NormaInfinitoLinha(A))
print(Norma1Coluna(B)>NormaInfinitoLinha(C)+NormaFrobenius(A))
print(NormaInfinitoLinha(D+C)<=NormaInfinitoLinha(D+A))
print(NormaFrobenius(A+B)>=NormaFrobenius(C+D))

False
False
True
False


In [107]:
# Matrizes

def IgualdadeMatrizes(A, B):
    return np.array_equal(A, B)


A  = np.array([[1,2],
               [0,1]])
B  = np.array([[1,1,1],[-1,1,-1],[1,0,0]])



v = np.array([1,
              2])


def GaussianElimination(A, b):
    n = len(A)
    X = [0] * n

    for k in range(n - 1):
        max_val = abs(A[k][k])
        max_index = k

        for i in range(k + 1, n):
            if abs(A[i][k]) > max_val:
                max_val = abs(A[i][k])
                max_index = i

        if max_index != k:
            A[k], A[max_index] = A[max_index], A[k]
            b[k], b[max_index] = b[max_index], b[k]

        if A[k][k] == 0:
            # O sistema é impossível ou não tem solução única
            # det(A) = 0
            return None
        else:
            for m in range(k + 1, n):
                F = (-1) * A[m][k] / A[k][k]
                A[m][k] = 0  # Evita uma iteração
                b[m] = b[m] + F * b[k]

                for l in range(k + 1, n):
                    A[m][l] = A[m][l] + F * A[k][l]

    X[n - 1] = b[n - 1] / A[n - 1][n - 1]

    for i in range(n - 2, -1, -1):
        X[i] = b[i]

        for j in range(i + 1, n):
            X[i] = X[i] - X[j] * A[i][j]

        X[i] = X[i] / A[i][i]

    return X


In [108]:
""" 

⎡⎣⎢100−120 13−4⎤  *  ⎥⎡⎣⎢x1 x2 x3⎤⎦ = ⎡⎣⎢2 13 −12⎤⎦⎥


"""

M = np.array([[1,-1,1],[0,2,3],[0,0,-4]])    
b = np.array([2,13,-12])

print(GaussianElimination(M, b), "\n")
print(np.linalg.solve(M, b))

[1.0, 2.0, 3.0] 

[1. 2. 3.]


## Sistemas Lineares

In [109]:
A = np.array([ [1, 2, -3],[1, 3 ,1],[2, 5, -4] ])
b= np.array([4,11,13])
z = np.zeros((3,3))





In [110]:
#print( SistemSolver(  GaussianElimination(  MatrizAumentada(  A,b  ) )  )  ) 

In [111]:
A = np.array([[-4, -3, 2, 1],[1, 2, 3, 4],[0, 5, -1, 3],[-3,2,-1/4,2]])

In [112]:
l,u = LUDecomposer(A)

## AFA 2

In [113]:
# Questão 1 EXO2

A = np.array([[1,0,0],[0,1,0],[0,0,1]])
b =  np.array([0,0,1])

x = [1,1,0]


m,n = A.shape
print(m!=n )

# False = Não é quadrada

np.dot(A,x) == b


print(SistemSolver(MatrizAumentada(A,b)))

print(PostoMatriz(MatrizAumentada(A,b)))


False
[0. 0. 1.]
[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 1.]
3


In [114]:
# Questão 2 EXO2

A = np.array([[2,2,1],[0,4,1],[2,0,1]])
b =  np.array([2,2,3])

l,u = LUDecomposer(A)

print("L = \n", l)
print()
print("U = \n",u)

#Resolvendo o sistema Ux = y
print()

print("x = ", SistemSolver(MatrizAumentada(u,SistemSolver(MatrizAumentada(l,b)))))

#Resolvendo o sistema Ly = b
print()
print("y = ", SistemSolver(MatrizAumentada(l,b)))

L = 
 [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 1.  -0.5  1. ]]

U = 
 [[2.  2.  1. ]
 [0.  4.  1. ]
 [0.  0.  0.5]]

x =  [-1. -1.  6.]

y =  [2. 2. 3.]


In [115]:
# Questão 3 EXO2

A = np.array([[1,0,-1],[0,1,0],[-1,0,1]])
B = np.array([[1,0],[2,30]])
C = np.array([[1,0,0],[0,2,0],[0,0,3]])
D = np.array([[1,-2],[-2,1]])


print(MatrizPositivaDefinida(A))
print(MatrizPositivaDefinida(B))
print(MatrizPositivaDefinida(C))
print(MatrizPositivaDefinida(D))



def DefinidaPositiva(A):
    
    # determinante da submatriz i:i é diferente de 0
    
    for i in range(len(A)):
        if np.linalg.det(A[0:i,0:i]) == 0:
            print("Não é definida positiva")
            return False    
        
print(DefinidaPositiva(A))

In [118]:
# Questão 4 EXO2



A = np.array([[2,0,0],[0,4,4],[0,4,6]])
b = np.array([2,2,3])

In [121]:
print(CholeskyDecomposer(A))

[[1.41421356 0.         0.        ]
 [0.         2.         0.        ]
 [0.         2.         1.41421356]]


In [125]:
# Gy = b

print("y = ", SistemSolver(MatrizAumentada(CholeskyDecomposer(A),b)))

y =  [1.41421356 1.         2.12132034]


In [127]:
print("x = ", SistemSolver(MatrizAumentada(CholeskyDecomposer(A).T,SistemSolver(MatrizAumentada(CholeskyDecomposer(A),b)))))

x =  [ 1.  -1.   1.5]
