In [1]:
import numpy as np 


In [39]:
def SomaVetores(x, y):
    
    np.sum(x, y)

def MultiplicaEscalarVetor(a, x):    
    np.dot(a, x)


def ProdutoInterno(x, y):
    return np.dot(x, y)

#Normas 

def Norma1(x):
    return np.sum(np.abs(x))
def Norma2(x):
    return np.sqrt(np.sum(np.abs(x)**2))
def NormaInfinito(x):
    return np.max(np.abs(x))
def Normap(x, p):
    return np.sum(np.abs(x)**p)**(1/p)
def NormaSoma(x, y):
    return np.sqrt(Norma2(x)**2 + Norma2(y)**2 + 2*ProdutoInterno(x, y))
def NormaSubtracao(x, y):
    return np.sqrt( (Norma2(x)) **2 + (Norma2(y))**2 - 2*ProdutoInterno(x, y))

# Distâncias

def DistanciaCaracteristicas(x, y):
    
    return NormaSubtracao(x, y)

def Vizinhanca(x,z):
    # X é o ponto base 
    # Z é uma lista de pontos, a qual queremos o de menor distância
    
    proximo = z[0]
    
    for i in range(len(z)):
        if DistanciaCaracteristicas(x, z[i]) < DistanciaCaracteristicas(x, proximo):
            proximo = z[i]
            
    return proximo


# Aplicação Normalização

def NormalizaVetor(x):
    return x/Norma2(x)

def BaseOrtonormal(beta,x):
    
    #x é o vetor que queremos a base ortonormal
    #beta é a base ortonormal
    xnormal = []
    
    if len(beta) != len(x):
        print("Erro, dimensões diferentes")
        return
    else:
        
        for i in range(len(beta)):
            
            xnormal.append(ProdutoInterno(x, beta[i])*beta[i])
        
        return xnormal

def AnguloVetores(x, y):
    
    return np.arccos(  ( ProdutoInterno(x, y)/(Norma2(x)*Norma2(y)) )  )    


def GramSchmidt(a, tol=1e-10):
    q = []
    for i in range(len(a)):
        qtilde = np.array(a[i], dtype=np.float64)  # Convert to float64 explicitly
        for j in range(i):
            qtilde -= np.dot(q[j], a[i]) * q[j]
        if np.linalg.norm(qtilde) < tol:
            print("Os vetores são linearmente dependentes.")
            return q
        print(qtilde)
        q.append(qtilde / np.linalg.norm(qtilde))
    return q




### Exercício 3.

Dado o conjunto V = {v1, v2, v3, v4, v5, v6}, onde
v1 = [1,2,3,4], 
v2 = [0,5,−1,3],
v3 = [−4,−3,2,1],
v4 = [−,1,−7,3,−7/3],
v5 = [1,−4,−6,-2],
v6 = [3,2,−1/4,2]

In [3]:
## Correção da questão 3 da lista de exercícios

# Verifica Ortogonalidade


v1 = [1,2,3,4]
v2 = [0,5,-1,3]
v3 = [-4,-3,2,1]
v4 = [-1,-7,3,-2.3333]
v5 = [1,-4,-6,-2]
v6 = [3,2,-0.25,2]

V = np.array([v1,v2,v3,v4,v5,v6],dtype="object")

for i in range(len(V)):
    for j in range(i,len(V)):
        if i != j:
            print("Produto interno entre v",i+1," e v",j+1,": ", ProdutoInterno(V[i],V[j]))

Produto interno entre v 1  e v 2 :  19
Produto interno entre v 1  e v 3 :  0
Produto interno entre v 1  e v 4 :  -15.3332
Produto interno entre v 1  e v 5 :  -33
Produto interno entre v 1  e v 6 :  14.25
Produto interno entre v 2  e v 3 :  -14
Produto interno entre v 2  e v 4 :  -44.9999
Produto interno entre v 2  e v 5 :  -20
Produto interno entre v 2  e v 6 :  16.25
Produto interno entre v 3  e v 4 :  28.6667
Produto interno entre v 3  e v 5 :  -6
Produto interno entre v 3  e v 6 :  -16.5
Produto interno entre v 4  e v 5 :  13.666599999999999
Produto interno entre v 4  e v 6 :  -22.4166
Produto interno entre v 5  e v 6 :  -7.5


In [4]:
# Verifica Angulos:


for i in range(len(V)):
    for j in range(i,len(V)):
        if i != j:
            print("Angulo entre v",i+1," e v",j+1,": ", AnguloVetores(V[i],V[j]))


Angulo entre v 1  e v 2 :  0.9442473545867198
Angulo entre v 1  e v 3 :  1.5707963267948966
Angulo entre v 1  e v 4 :  1.9270040069334677
Angulo entre v 1  e v 5 :  2.49480519746212
Angulo entre v 1  e v 6 :  0.8894441470679866
Angulo entre v 2  e v 3 :  2.0175602879101473
Angulo entre v 2  e v 4 :  2.816162498730185
Angulo entre v 2  e v 5 :  2.035070208212683
Angulo entre v 2  e v 6 :  0.8433509628782423
Angulo entre v 3  e v 4 :  0.860622133841933
Angulo entre v 3  e v 5 :  1.7164055673877163
Angulo entre v 3  e v 6 :  2.38808423797738
Angulo entre v 4  e v 5 :  1.3433484740176547
Angulo entre v 4  e v 6 :  2.3131372783928406
Angulo entre v 5  e v 6 :  1.8136700887016526


In [5]:
np.arccos((ProdutoInterno(v1,v3)/Norma2(v1)*Norma2(v3)))

1.5707963267948966

In [6]:
# Gerar todos os possíveis subconjuntos de v com 4 vetores e verificar se formam uma base

# C 6,4 = 15

#Separar as combinações de quatro vetores possíveis

for i in range(len(V)):
    for j in range(i+1,len(V)):
        for k in range(j+1,len(V)):
            for l in range(k+1,len(V)):
                print("Combinação: v%d,v%d,v%d,v%d"%(i,j,k,l),V[i],V[j],V[k],V[l])
                #print(V[i],V[j],V[k],V[l])
                # verificar se formam uma base
                A = np.array([V[i],V[j],V[k],V[l]], dtype="float64")
                print(A)
                det = np.linalg.det(A)
                if det != 0:
                    
                    print("Formam uma base, det: ", det)
                else:
                    print("LD!!")

Combinação: v0,v1,v2,v3 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [-1 -7 3 -2.3333]
[[ 1.      2.      3.      4.    ]
 [ 0.      5.     -1.      3.    ]
 [-4.     -3.      2.      1.    ]
 [-1.     -7.      3.     -2.3333]]
Formam uma base, det:  0.0024999999999941766
Combinação: v0,v1,v2,v4 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [1 -4 -6 -2]
[[ 1.  2.  3.  4.]
 [ 0.  5. -1.  3.]
 [-4. -3.  2.  1.]
 [ 1. -4. -6. -2.]]
Formam uma base, det:  534.0000000000001
Combinação: v0,v1,v2,v5 [1 2 3 4] [0 5 -1 3] [-4 -3 2 1] [3 2 -0.25 2]
[[ 1.    2.    3.    4.  ]
 [ 0.    5.   -1.    3.  ]
 [-4.   -3.    2.    1.  ]
 [ 3.    2.   -0.25  2.  ]]
Formam uma base, det:  133.4999999999999
Combinação: v0,v1,v3,v4 [1 2 3 4] [0 5 -1 3] [-1 -7 3 -2.3333] [1 -4 -6 -2]
[[ 1.      2.      3.      4.    ]
 [ 0.      5.     -1.      3.    ]
 [-1.     -7.      3.     -2.3333]
 [ 1.     -4.     -6.     -2.    ]]
Formam uma base, det:  178.00169999999994
Combinação: v0,v1,v3,v5 [1 2 3 4] [0 5 -1 3] [-1 -7 3 -2.3333] [3 2 -0.

In [7]:
Z  = np.array([[ 1,  2,  3, 4],[ 0,  5,-1, 3],[-4,-3, 2, 1],[ 1,-4,-6,-2]], dtype="float64")

h = np.array([[1,0],[0,2]], dtype="float64")

In [8]:
np.linalg.det(Z)

534.0000000000001

In [9]:
# Calcular Normas 1,2,infinito para cada vetor

for i in range(len(V)):
    print("Norma 1 de v%d: "%(i+1), Norma1(V[i]))
    print("Norma 2 de v%d: "%(i+1), Norma2(V[i]))
    print("Norma infinito de v%d: "%(i+1), NormaInfinito(V[i]))

Norma 1 de v1:  10
Norma 2 de v1:  5.477225575051661
Norma infinito de v1:  4
Norma 1 de v2:  9
Norma 2 de v2:  5.916079783099616
Norma infinito de v2:  5
Norma 1 de v3:  10
Norma 2 de v3:  5.477225575051661
Norma infinito de v3:  4
Norma 1 de v4:  13.3333
Norma 2 de v4:  8.027720030618905
Norma infinito de v4:  7
Norma 1 de v5:  13
Norma 2 de v5:  7.54983443527075
Norma infinito de v5:  6
Norma 1 de v6:  7.25
Norma 2 de v6:  4.130677910464576
Norma infinito de v6:  3


In [25]:
### Questão 6

def a(x):
    
    return np.max(np.abs(x[:-1])) # Norma infinito de 1 ate n-1

def b(x):
    return np.sum(np.abs(x**3))

def c(x):
    return np.sum(np.abs(x**2)**(1/2))

def d(x):
    
    soma = 0
    for i in range(len(x)):
       soma += np.abs((2**-i)*x[i])
    
    return soma

In [26]:
# Verificar Norma:

#||u|| >= 0
#||u+v|| <= ||u|| + ||v||
#||au|| = |a|*||u||

u = np.array([1,0,1])
v = np.array([-2,1,0])

print(a(u+v) <= a(u) + a(v),a(2*u) == 2*a(u),a(u) >= 0 )
print(b(u+v) <= b(u) + b(v),b(2*u) == 2*b(u),b(u) >= 0 )
print(c(u+v) <= c(u) + c(v),c(2*u) == 2*c(u),c(u) >= 0 )
print(d(u+v) <= d(u) + d(v),d(2*u) == 2*d(u),d(u) >= 0 )



True True True
True False True
True True True
True True True


In [40]:
# Questão 8


a1 = np.array([1,1,0])
a2 = np.array([0,1,1])
a3 = np.array([1,0,1])

beta = [a1,a2,a3]


# base ortonormal

beta = GramSchmidt(beta)

for i in range(len(beta)):
    print("Norma 2 do vetor %d: "%(i+1), Norma2(beta[i]))

[1. 1. 0.]
[-0.5  0.5  1. ]
[ 0.66666667 -0.66666667  0.66666667]
Norma 2 do vetor 1:  0.9999999999999999
Norma 2 do vetor 2:  1.0
Norma 2 do vetor 3:  1.0
